- name: install steam
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  tasks:
#---------------------------------------------------------------------------------------------
  - name: ensure 'steam' is at the latest version
    become: true
    become_method: sudo
    command: "snap install steam"
    when: install_steam == 1
