- name: install signal-desktop
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  tasks:
#---------------------------------------------------------------------------------------------
  - name: installing signal-desktop via snap
    become: true
    become_method: sudo
    command: snap install signal-desktop
    when: install_signal == 1
