- name: install HyperHDR
  hosts: all
  remote_user: "{{ssh_user}}"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "download package: 'HyperHDR-20.0.0.0.noble-x86_64.deb'"
    command: wget https://github.com/awawa-dev/HyperHDR/releases/download/v20.0.0.0/HyperHDR-20.0.0.0.noble-x86_64.deb
    when: install_hyperhdr == 1
#---------------------------------------------------------------------------------------------
  - name: "install hyperhdr"
    become: true
    become_method: sudo
    command: dpkg -i ./HyperHDR-20.0.0.0.noble-x86_64.deb
    when: install_hyperhdr == 1
#---------------------------------------------------------------------------------------------
  - name: "remove package: 'HyperHDR-20.0.0.0.noble-x86_64.deb'"
    command: rm -f ./HyperHDR-20.0.0.0.noble-x86_64.deb
    when: install_hyperhdr == 1
