- name: install gamescope
  hosts: all
  remote_user: "{{ssh_user}}"
  tasks:
  - name: upgrade installed apt packages
    become: true
    become_method: sudo
    apt:
      name: "*"
      state: latest
      update_cache: yes
      cache_valid_time: 30 #One day 
    when: install_gamescope == 1
#---------------------------------------------------------------------------------------------
  - name: ensure 'meson' is at the latest version
    become: true
    become_method: sudo
    apt:
      name: meson
      state: latest
    when: install_gamescope == 1
#---------------------------------------------------------------------------------------------
  - name: ensure 'git' is at the latest version
    become: true
    become_method: sudo
    apt:
      name: git
      state: latest
    when: install_gamescope == 1
#---------------------------------------------------------------------------------------------
  - name: checking if '/home/{{ssh_user}}/repos/gamescope' exists
    stat:
      path: "/home/{{ssh_user}}/repos/gamescope"
    register: has_gamescope_repo
    when: install_gamescope == 1
#---------------------------------------------------------------------------------------------
  - name: "clone repository"
    command: git clone https://github.com/ValveSoftware/gamescope
    args:
      chdir: "/home/{{ssh_user}}/repos/"
    when: install_gamescope == 1 and not has_gamescope_repo.stat.exists
#---------------------------------------------------------------------------------------------
  - name: "setup build with meson"
    command: meson setup build/
    args:
      chdir: "/home/{{ssh_user}}/repos/gamescope"
    when: install_gamescope == 1
#---------------------------------------------------------------------------------------------
  - name: "build from sources with ninja"
    command: ninja -C build/
    args:
      chdir: "/home/{{ssh_user}}/repos/gamescope"
    when: install_gamescope == 1
